---
include:
  - "**/*.rb"
exclude:
  - features/**/*
  - node_modules/**/*
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
require_paths: []
plugins: []
max_files: 5000
